export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const USERS_ROUTE = '/users'
export const MESSENGER_ROUTE = '/messenger'
export const PROFILE_ROUTE = '/profile'
export const REGISTRATION_ROUTE = '/registration'
export const FRIENDS_ROUTE = '/'
export const LOCALSTORAGE_ITEM = 'react-websocket'
